<a href="https://colab.research.google.com/github/Sankalpkarn/Data_Analytics/blob/main/DAY3_DA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=[10,20.5,'Python',True]
print(a)
print(type(a))

[10, 20.5, 'Python', True]
<class 'list'>


In [ ]:
import numpy as np
a=np.array([10,20,30,40,50])
print(a)
print(type(a))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [ ]:
#zeroes
a=np.zeros((4,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
#ones
a=np.ones((4,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
a=np.ones((4,2))
print(a+32)

[[33. 33.]
 [33. 33.]
 [33. 33.]
 [33. 33.]]


In [ ]:
a=np.ones((4,2))
print(a*12)

[[12. 12.]
 [12. 12.]
 [12. 12.]
 [12. 12.]]


In [ ]:
#linspace
a=np.linspace(0,10,20)
print(a)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [ ]:
a=np.linspace(0,10,4)
print(a)

[ 0.          3.33333333  6.66666667 10.        ]


In [ ]:
a=np.arange(0,24,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [ ]:
a=np.random.random(10)#it will always lies between 0 and 1
print(a)

[0.28533415 0.05180803 0.91069075 0.70485754 0.23915749 0.5816935
 0.95595342 0.99454433 0.27644917 0.66449753]


In [ ]:
a=np.random.random(10)
print(a*10)

[8.31130625 0.90908735 2.04136646 5.50059062 6.99256779 2.19306019
 2.97072285 3.16088541 1.71345818 8.52356171]


In [ ]:
a=np.arange(24,dtype=float)#applied only in few cases only, others data type vlaues can't be changed
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]


In [ ]:
a=np.full((3,4),5.5)
print(a)

[[5.5 5.5 5.5 5.5]
 [5.5 5.5 5.5 5.5]
 [5.5 5.5 5.5 5.5]]


#list
#tuple
#zeros
#ones
#full
#linspace
#arange
#random.random

- create a data with the help of list for 10 different values
- create a data with the help of tuple for 5 different values
- create a data with the help of zeroes for 3 rows and 5 columns
- create a data with the help of ones for 6 rows and 7 columns
- create a data with the all element as 44 with full
- create a data with the all element as 44 without using full
- create a data with the help of linspace and get 20 data points between 12 and 24
- create a data with the help of arrange between 15 and 34 with step size 3
- create a data with the help of random.random for 25 points

In [ ]:
#create a data with the help of list for 10 different values
a=[10,20.5,'Python',True,25,32.6,'RAM',False,13,'hello']
print(a)
print(type(a))

[10, 20.5, 'Python', True, 25, 32.6, 'RAM', False, 13, 'hello']
<class 'list'>


In [ ]:
#create a data with the help of tuple for 5 different values
a=(1,2,3,4,5)
print(a)
print(type(a))

(1, 2, 3, 4, 5)
<class 'tuple'>


In [ ]:
#create a data with the help of zeroes for 3 rows and 5 columns
a=np.zeros((3,5))
print(a)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a data with the help of ones for 6 rows and 7 columns
a=np.ones((3,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#create a data with the all element as 44 with full
a=np.full((3,5),44)
print(a)

[[44 44 44 44 44]
 [44 44 44 44 44]
 [44 44 44 44 44]]


In [ ]:
#create a data with the all element as 44 without using full
a=np.ones((3,5))
print(a+43)

[[44. 44. 44. 44. 44.]
 [44. 44. 44. 44. 44.]
 [44. 44. 44. 44. 44.]]


In [ ]:
#create a data with the help of linspace and get 20 data points between 12 and 24
a=np.linspace(12,34,20)
print(a)

[12.         13.15789474 14.31578947 15.47368421 16.63157895 17.78947368
 18.94736842 20.10526316 21.26315789 22.42105263 23.57894737 24.73684211
 25.89473684 27.05263158 28.21052632 29.36842105 30.52631579 31.68421053
 32.84210526 34.        ]


In [ ]:
#create a data with the help of arrange between 15 and 34 with step size 3
a=np.arange(15,34,3)
print(a)

[15 18 21 24 27 30 33]


In [ ]:
#create a data with the help of random.random for 25 points
a=np.random.random(25)
print(a)

[0.25104541 0.80415648 0.38341616 0.09074686 0.07324697 0.64939203
 0.16484638 0.20219279 0.19994879 0.93162036 0.92724398 0.54999612
 0.96970619 0.95320889 0.09513155 0.67556983 0.75551701 0.04894695
 0.89845154 0.61424911 0.84303778 0.83946058 0.06195472 0.28657702
 0.22942292]


In [ ]:
a=np.array([20,30,40,50,60])
print(a)
print(a.ndim)
print(a.size)
print(a.shape)

[20 30 40 50 60]
1
5
(5,)


In [ ]:
a=np.array([[[20,30,40],
            [50,60,70]]])
print(a)
print(a.ndim)
print(a.size)#no. of elements
print(a.shape)#it give 1 for no. of arrays

[[[20 30 40]
  [50 60 70]]]
3
6
(1, 2, 3)


In [ ]:
a=np.array([
            [[20,30,40],
            [50,60,70],
            [80,90,100]],
            [[20,30,40],
            [50,60,70],
            [80,90,100]]
            ])
print(a)
print(a.ndim)
print(a.size)#no. of elements
print(a.shape)#it give 2 for no. of arrays

[[[ 20  30  40]
  [ 50  60  70]
  [ 80  90 100]]

 [[ 20  30  40]
  [ 50  60  70]
  [ 80  90 100]]]
3
18
(2, 3, 3)


#Slicing And Indexing

In [37]:
a=[10,20,30,40,50,60]
a[0:3]

[10, 20, 30]

In [38]:
a=np.array([10,20,30,40,50,60])
a[0:3]

array([10, 20, 30])

In [44]:
a=np.array([[10,20,30,],
    [40,50,60]])
a[0,0]

10

In [53]:
a=np.array([[10,20,30,],
            [40,50,60]])
#10,20
a[0,0:2]

array([10, 20])

In [55]:
a=np.array([[10,20,30,],
            [40,50,60]])
#10,20
#a(r,c)
#a(rs:re,cs:ce)s = start & e = end
a[0:2,0:2]
a[0:2,2:3]

array([[30],
       [60]])